mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^text/',include('text.urls')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/text/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import logout

app_name = 'text'

urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name="home"),
    url(r'^about/$', views.AboutView.as_view(), name="about"),
    url(r'^topics/$', views.IndexView.as_view(), name="index"),
    url(r'^logout/$',views.logout_view,name='logout'),
    url(r'^login/$',views.login_view, name='login'),
    url(r'^register/$',views.UserFormView.as_view(),name='register'),
    url(r'^(?P<pk>[0-9]+)$',views.DetailView.as_view(), name='detail'),
    url(r'album/add/$',views.AlbumCreate.as_view(), name="album-add"),
    url(r'album/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name='album-update'),
    url(r'album/(?P<pk>[0-9]+)/delete/$',views.AlbumDelete.as_view(), name='album-delete'),
]

mysite/text/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.
class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.FileField()

    def get_absolute_url(self):
        return reverse('text:detail', kwargs={'pk':self.pk})

    def __str__(self):
        return self.album_title + " - " + self.artist

class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

mysite/text/forms.py
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth import get_user_model, authenticate

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Enter password'}))
    email = forms.EmailField(widget= forms.EmailInput
                           (attrs={'placeholder':'Enter email'}))
    username = forms.CharField(widget=forms.TextInput
            (attrs={'placeholder': 'Enter username'}))
    class Meta:
        model = User
        fields = ['username','email','password']


User = get_user_model()

class UserLoginForm(forms.Form):
    username = forms.CharField(widget= forms.TextInput
                           (attrs={'placeholder':'Enter username'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Enter password'}))
    def clean(self, *args, **kwargs):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        if username and password:
            user = authenticate(username=username, password=password)
            if not user:
                raise  forms.ValidationError("This user doesn't exist")
            if not user.check_password(password):
                raise forms.ValidationError("Incorrect password")
            if not user.is_active:
                raise forms.ValidationError("This user is not longer active.")
        return super(UserLoginForm, self).clean(*args,**kwargs)

mysite/text/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login,logout
from django.core.urlresolvers import reverse_lazy
from django.views.generic import View
from .models import Album
from .forms import UserForm, UserLoginForm
from django.contrib.auth.decorators import login_required

#@login_required()
class IndexView(generic.ListView):
    template_name = 'text/index.html'
    context_object_name = 'all_albums'

    def get_queryset(self):
        return Album.objects.all()

class HomeView(generic.ListView):
    template_name = 'text/home.html'
    context_object_name = 'all_albums'
    def get_queryset(self):
        return Album.objects.all()

class AboutView(generic.ListView):
    template_name = 'text/about.html'
    context_object_name = 'all_albums'
    def get_queryset(self):
        return Album.objects.all()

def logout_view(request):
    logout(request)
    return redirect('text:home')

class DetailView(generic.DetailView):
    model = Album
    template_name = 'text/detail.html'

class AlbumCreate(CreateView):
    model = Album
    fields = ['artist','album_title','genre','album_logo']

class AlbumUpdate(UpdateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']

class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('text:index')

def login_view(request):
    form = UserLoginForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(username=username,password=password)
        login(request,user)
        #print(request.user.is_authenticated())
        return redirect('text:home')
    return render(request, 'text/form.html', {'form':form})

class UserFormView(View):
    form_class = UserForm
    template_name = 'text/registration_form.html'

    #display blank form
    def get(self,request):
        form = self.form_class(None)
        return render(request,self.template_name,{'form':form})

    #process form data
    def post(self,request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)
            #cleaned (normalized) data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            email = form.cleaned_data['email']
            user.set_password(password)
            user.save()

            #returns User objects if credentials are correct
            user = authenticate(username=username,password=password,email=email)

            if user is not None:
                if user.is_active:
                    login(request,user)
                    return redirect('text:home')
        return render(request, self.template_name, {'form':form})

mysite/text/templates/text/about.html
<!-- Loads the path to your static files -->
{% extends 'text/base.html' %}
{% block title %}Home{% endblock %}
{% block body %}
<div class="container text-center" style="background:gray; margin-top:-2%;height:80%">
    <div class="container-fluid text-center" style="color:white"><!--style="background-color: #474e5d; color: #ffffff;">-->
  <h3>What Am I?</h3>
      <h4>A cryptographic nonce (number used once) to whitelist inline styles in a style-src Content-Security-Policy. The server must generate a unique nonce value each time it transmits a policy. It is critical to provide a nonce that cannot be guessed as bypassing a resource’s policy is otherwise trivial.</h4>
</div>
<div class="container-fluid text-center bg-grey">
  <!--<h2 style="color:white">Portfolio</h2>-->
  <div class="row text-center">
    <div class="col-sm-4">
      <div class="thumbnail">
        <img src="https://static1.squarespace.com/static/5914d841e6f2e109b2a338f6/t/59c00376bce176b2597343d4/1498249483027/" alt="Paris">
        <p><strong>Paris</strong></p>
        <p>Yes, we built Paris</p>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="thumbnail">
        <img src="https://static1.squarespace.com/static/5914d841e6f2e109b2a338f6/t/59385bd2e6f2e16e6a20705f/1500058908009/Boy_Texting?format=300w" alt="New York">
        <p><strong>New York</strong></p>
        <p>We built New York</p>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="thumbnail">
        <img src="https://static1.squarespace.com/static/5914d841e6f2e109b2a338f6/t/59c04bb4d55b417f6036f492/1505774520777/howitworks-06.png?format=300w" alt="San Francisco">
        <p><strong>San Francisco</strong></p>
        <p>Yes, San Fran is ours</p>
      </div>
    </div>
</div>
<div class="container-fluid text-center" style="color:white"> <!--style="background-color: #ffffff;color: #555555;">-->
  <h3>Where To Find Me?</h3>
    <h4>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</h4>
</div>
    <br/>
</div>
{% endblock %}

mysite/text/templates/text/album_form.html
{% extends 'text/base.html' %}
{% block title %}Add a New Album{% endblock %}
{% block album_active %}active{% endblock %}

{% block body %}
<div class="container" style="color:white; background:gray; margin-top:-2%;height:80%">
    <div class="row">
        <div class="col-sm-12 col-md-7" style="margin-left:35%;">
                    <h3>From image to text</h3>
                    {% if error_message %}
                        <p><strong>{{error_message}}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'text/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-default">Submit</button>
                            </div>
                        </div>
                    </form>
        </div>
    </div>
    <br/>
<br/>
<br/><br/><br/><br/>
    <br/>
<br/>
<br/><br/><br/>
</div>

{% endblock %}

mysite/text/templates/text/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Textasy{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'text/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'text:home' %}">Textasy</a>
        </div>
        <!-- Items -->
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{% url 'text:index' %}">
                        <span class="glyphicon glyphicon-envelope" area-hidden="true"></span>&nbsp;
                        Topics
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'text:album-add' %}">
                            <span class="glyphicon glyphicon-file" area-hidden="true"></span>&nbsp;
                        Texts
                    </a>
                </li>
            </ul>
            <!--
            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form> -->
            <ul class="nav navbar-nav navbar-right">
                    <li class="">
                        <a href="{% url 'text:home' %}">
                        <!--<a href="{% url 'text:album-add' %}">
                            <span class="glyphicon glyphicon-plus" area-hidden="true"></span>&nbsp;
                            Add Topic -->
                            <span class="glyphicon glyphicon-home" area-hidden="true"></span>&nbsp;
                            Home
                        </a>
                    </li>
                    <li class="">
                        <a href="{% url 'text:about' %}">
                            <span class="glyphicon glyphicon-text-color" area-hidden="true"></span>&nbsp;
                            About
                        </a>
                    </li>
                    <li class="">
                        <a href="{% url 'text:register' %}">
                            <span class="glyphicon glyphicon-ok-sign" area-hidden="true"></span>&nbsp;
                            Register
                        </a>
                    </li>
                    <li class="">
                        <a href="{% url 'text:login' %}">
                            <span class="glyphicon glyphicon-user" area-hidden="true"></span>&nbsp;
                            Login
                        </a>
                    </li>
                    <li class="">
                        <a href="{% url 'text:logout' %}">
                            <span class="glyphicon glyphicon-off" area-hidden="true"></span>&nbsp;
                            Logout
                        </a>
                    </li>
            </ul>
        </div>
        </div>
    </nav>
{% block body %}
    {% endblock %}
<footer class="container-fluid text-center">
  <p>Web-site Made By "Blackberry Pie" team</p>
</footer>
</body>
</html>

mysite/text/templates/text/detail.html
{% extends 'text/base.html' %}
{% block title %}{{ album }}{% endblock %}
{% block albums_active %}active{% endblock %}
{% block body %}

<div class="container" style="background:gray; margin-top:-1.5%;">
    <div class="row">
        <!-- Left Album Info -->

        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'text:detail' album.id %}">
                        {% if album.album_logo %}
                            <img src="{{ album.album_logo.url }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1>{{ album.album_title }} </h1>
                    <!--<h2>{{ album.artist }} <small>{{ album.genre }}</small></h2> -->
                </div>
            </div>
        </div>
        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">
            <ul class="nav nav-pills" style="margin-bottom:10; color:white">
                <li role="presentation" class=""><a style="color:white" href="{% url 'text:detail' album.id %}">View All</a></li>
                <li role="presentation"><a style="color:white" href="#">Add New Image</a></li>
            </ul>
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>All Texts</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <table class="table">
                        <thead>
                        <tr>
                            <th>Title</th>
                            <th>Image</th>
                            <th>Save File</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for song in album.song_set.all %}
                            <tr>
                                <td>{{ song.song_title }}</td>
                                <td>
                                    <a href="{% url 'text:detail' album.id %}">
                                        <img src="{{ album.album_logo.url }}" style="height:50px;width:100px">
                                    </a>
                                </td>
                                <td>
                                    <a target="_blank" href="{{ song.audio_file.url }}">
                                        <button type="button" class="btn btn-success btn-xs">
                                            <span class="glyphicon glyphicon-download"></span>&nbsp; Save
                                        </button>
                                    </a>
                                </td>
                                <td>
                                    <form action="#" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="song_id" value="{{ song.id }}" />
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mysite/text/templates/text/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{field.errors}}</span>
        </div>
        <!--<label class="control-label col-sm-2">{{field.label_tag}}</label> -->
        <div class="col-sm-10">{{field}}</div>
    </div>
{% endfor %}

mysite/text/templates/text/form.html
{% extends 'text/base.html' %}
{% block title %}Login{% endblock %}
{% block body %}
<div class="container" style="background:gray; margin-top:-2%;height:80%">
    <div class="col-sm-6 col-sm-offset-3">
        <h3 style="color:white">Login</h3><br/>
        <form class="form-horizontal" method="post" action="" enctype="multipart/form-data">
            {% csrf_token %}
            {% include 'text/form-template.html' %}
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-default">Submit</button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

mysite/text/templates/text/home.html
<!-- Loads the path to your static files -->
{% extends 'text/base.html' %}
{% block title %}Home{% endblock %}
{% block body %}
<div class="container-fluid" style="position:relative;">
    <img style="height:400px;width:100%;margin-top:-1.5%;-webkit-filter: grayscale(150%); filter: grayscale(150%);" src="http://dougbelshaw.com/blog/wp-content/uploads/2012/01/evernote-book-phone.jpg">
    <div style="position:absolute;top: 30%; right:5%; color:white;" class="col-sm-5" style="float:right">
    <h2>TEXTASY - is a application
    to get out the text from the
    textbooks by taking a photo
    from any camera</h2></div>
</div>
<div class="container-fluid">
  <h2 style="text-align:center">ABOUT</h2>
  <div class="row text-center">
    <div class="col-sm-6">
     <div class="col-sm-3">
      <span style="font-size:70px; padding-top:30%" class="glyphicon glyphicon-off"></span>
     </div>
        <div class="col-sm-9 text-left">
      <h4>Upload a photo</h4>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
        </div>
    </div>
    <div class="col-sm-6">
        <div class="col-sm-9 text-right">
      <h4>Saved documents</h4>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
    </div>
    <div class="col-sm-2">
      <span style="font-size:70px; padding-top:30%" class="glyphicon glyphicon-heart"></span>
        </div>
</div>
    </div>
    <br><br>
  <div class="row text-center">
    <div class="col-sm-6">
        <div class="col-sm-3">
      <span style="font-size:70px; padding-top:30%" class="glyphicon glyphicon-leaf"></span>
        </div>
    <div class="col-sm-9 text-left">
      <h4>Converted</h4>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
    </div>
</div>
    <div class="col-sm-6">

    <div class="col-sm-9 text-right">
      <h4>Translate</h4>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
    </div>
    <div class="col-sm-2">
      <span style="font-size:70px; padding-top:30%" class="glyphicon glyphicon-certificate"></span>
            </div>
</div>
</div>
    <div class="container-fluid">
        <iframe width="100%" height="400"
            src="https://www.youtube.com/embed/tgbNymZ7vqY">
        </iframe>
    </div>
    <div class="container-fluid text-center" style="background: gray; color:white">
        <h5>During the summer holidays before I headed to university I worked in a secondhand bookshop on </h5>
        <h5>   Broad Street in Oxford. And then, to help support myself during my MA in Modern History</h5>
           <h5> I worked in Waterstones bookshop in Newcastle. I love books.</h5><br>
        <p><a style="color:white" href="{% url 'text:register' %}">REGISTER NOW</a></p>
    </div>
</div>
{% endblock %}

mysite/text/templates/text/index.html
<!-- Loads the path to your static files -->
{% extends 'text/base.html' %}
{% block title %}Albums{% endblock %}
{% block body %}
<div class="container-fluid" style="background:gray; margin-top:-1.5%;">
    <div class="col-sm-12">
        <h3 style="color:white">{{ user.username }}'s Topics</h3>
    </div>
    {% for album in all_albums %}
    <div class="col-sm-6 col-lg-4">
                    <div class="thumbnail">
                        <a href="{% url 'text:detail' album.id %}">
                            <img src="{{ album.album_logo.url }}" style="height:200px;width:300px">
                        </a>
                        <div class="caption">
                            <h2>{{ album.album_title }}</h2>
                            <!-- <h4>{{ album.artist }}</h4>-->
                            <!-- View Details -->
                            <a href="{% url 'text:detail' album.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>
                            <!-- Delete Album -->
                            <form action="{% url 'text:album-delete' album.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="album_id" value="{{ album.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>
                            <!-- Favorite Album -->
                           <!-- <a href="#" class="btn btn-default btn-sm btn-favorite">
                                <span class="glyphicon glyphicon-star {% if album.is_favorite %}active{% endif %}"></span>
                            </a> -->
                        </div>
                    </div>
                </div>
</div>
    {% endfor %}
{% endblock %}

mysite/text/templates/text/registration_form.html
{% extends 'text/base.html' %}
{% block title %}Register{% endblock %}
{% block body %}
<div class="container-fluid">
    <div class="col-sm-5">
                    {% if error_message %}
                        <p><strong>{{error_message}}</strong></p>
                    {% endif %}
                    <h3>Registration</h3><br/>
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'text/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-default">Register</button>
                            </div>
                        </div>
                    </form>
        </div>
</div>
{% endblock %}